### ISSUE TITLE
PR-138: General Issues

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#166]
I've been playing with the KKS version of the plugin from PR-138.

Notable issues:

Texture naming convention is different between the two games. KKS seems to short-hand texture names.

_MainTex is shorthanded to _MT
_ColorMask is shorthanded to _CM
_DetailMask is shorthanded to _DM
_NormalMap and _NormalMapDetail are shorthanded to _NMP and _NMPD [new mexico police department?]
_liquidmask is shorthanded to _lqdm
_LineMask is shorthanded to _LM
_ColorMask is shorthanded to _CM

This causes an issue during the "Import shader" step.

Normal maps in KKS seem to be a red color, instead of the black and white ones that usually get spat out in KK.

**Comment by MediaMoots** [comment]
> This causes an issue during the "Import shader" step.

Could you share the card please?

**Comment by poisenbery** [comment]
This was actually my fault.
I used the KKS version of the plugin without updating the blender scripts.
Really sorry about this.

The only "issue" regarding textures is when the face type is 2 or 3, which is essentially the same as #163 
So it's not really an issue then.

Again, really sorry and thank you for adding KKS support.
I've been testing multiple cards and the improvements are VERY nice.

**Comment by poisenbery** [comment]
The KKS version of the exporter is having issues with the Sailor type uniform when there is an accessory. 
[KKS console log]
```
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

.new SMRData.ctor(SkinnedMeshRenderer)
void PmxBuilder.CreateMeshList()
void PmxBuilder.BuildStart_OG()
```


A folder with a few of the textures gets generated, but the PMX doesn't get built. 
![Screenshot (618)](https://user-images.githubusercontent.com/78466408/172038335-4275426c-33f2-4368-b56b-71c2ef48f7ed.png)

Jacket with accessory seems to be fine. Other types seem to function fine as well, but I haven't been able to test everything yet.

**Comment by poisenbery** [comment]
Eyes are all opened way too much. I've been attempting to troubleshoot this for about an hour but am unable to identify the cause. 
From what I have observed, it is happening to every model.
The effect is EXTREMELY obvious on characters with rectangle shaped eyes.
![Screenshot (621)](https://user-images.githubusercontent.com/78466408/172040441-cc3e40ce-db74-410f-bc24-a99232e6df15.png)
![Screenshot (622)](https://user-images.githubusercontent.com/78466408/172040445-79829246-86b0-48c2-9628-9bc04c5adae5.png)
![Screenshot (620)](https://user-images.githubusercontent.com/78466408/172040446-baef74cc-15cc-4ee0-a612-e5484f0ae72b.png)


When I use a different method to import the PMX, the problem seems to still persist. I'm not sure if I have a mod conflict that is doing this. I made sure to disable anything affecting the eyes but I can't figure out why this one is happening.

**Comment by MediaMoots** [comment]
![image](https://user-images.githubusercontent.com/81146974/172041050-6b2e140c-6518-4236-a730-677126c9a9fe.png)
I'm scared, mom plz save me...

JK

This is because KK sets the shapekeys to a certain value during runtime, but KKBP Exporter exports the original shapekeys from the mesh, so you can just set the shapekeys in blender to match the openness you want.

**Comment by poisenbery** [comment]
> This is because KK sets the shapekeys to a certain value during runtime, but KKBP Exporter exports the original shapekeys from the mesh, so you can just set the shapekeys in blender to match the openness you want.

Sounds simple enough.
I found that 0.1-.02 with the eye's closed shapekey seems to do the trick.

Was kind of concerning because it didn't happen in the KK version.

**Comment by MediaMoots** [comment]
> The KKS version of the exporter is having issues with the Sailor type uniform when there is an accessory.

I think its fixed in 2.02, please try it out

**Comment by MediaMoots** [comment]
> Was kind of concerning because it didn't happen in the KK version.

Oh really!

Could you share the card that has this issue in KKS but not in KK?

**Comment by poisenbery** [comment]
> Could you share the card that has this issue in KKS but not in KK?

It's literally every single card I do with the KKBP exporter.

When I use the exporter that I made, it doesn't have the eyes opened like that. That's the main reason I'm so confused and think it's a bug.

I won't go into detail, but I'm extra familiar with the eyes on this particular character. 
![Screenshot (626)](https://user-images.githubusercontent.com/78466408/172047469-9f40487c-562b-4a3f-887b-62887e8ac638.png)
![Screenshot (627)](https://user-images.githubusercontent.com/78466408/172047472-52f62387-8495-4207-bf00-a7217617373c.png)
.

**Comment by MediaMoots** [comment]
> When I use the exporter that I made

Is it the one in the fork?

**Comment by poisenbery** [comment]
> Is it the one in the fork?

https://github.com/Snittern/KoikatsuPmxExporterReverseEngineered

it's basically this with the KKS references.
I haven't updated my fork with the compiled .dll yet because I haven't fixed the texture exporting yet.

**Comment by MediaMoots** [comment]
Ok yeah, the old plugin had a bug where it exported the shapekeys with KK's corrections applied. but I fixed it in the new plugin so that it exports the original shapekeys.

So, it's not a bug.

**Comment by poisenbery** [comment]
Ahhhh I understand.
It's expected behavior that I did not expect. 

If only...I could read the source code ;)

**Comment by poisenbery** [comment]
> I think its fixed in 2.02, please try it out

My dear Marnie is still having the same problem. 
From what I understand, it's her bra causing the issue. A few other of the "bras" that are a 1 piece set and  grey out the underwear slot cause this as well. I have a 2B card that causes the problem but it's too big to upload here.
![KK_106642](https://user-images.githubusercontent.com/78466408/172048739-82059b65-7716-4d04-a871-b68d67cdea32.png)
 
 The 2B card causing the issue can be found on Bepis by turning on "Featured Only" and hitting search. She'll be the 2nd card on the Koikatsu list.
 
 Error Message:

```
[Warning:  HarmonyX] AccessTools.Field: Could not find field for type UnityEngine.GameObject and name objSleeves01
[Warning:  HarmonyX] AccessTools.Field: Could not find field for type UnityEngine.GameObject and name objSleeves02
[Warning:  HarmonyX] AccessTools.Field: Could not find field for type UnityEngine.GameObject and name objSleeves03
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

.new ClothesData.ctor(string, int, ChaClothesComponent)
void PmxBuilder.CreateClothesData()
void PmxBuilder.BuildStart_OG()
```

**Comment by MediaMoots** [comment]
> My dear Marnie is still having the same problem.

Thanks for all the testing!

I think its fixed now, please try out v2.04 in the PR

**Comment by poisenbery** [comment]
Sorry for the delay.
I found a minor hiccup with the detail map texture.
It was being exported but wasn't referenced at all in the shader pack or blender script itself.

I added a new texture node and named it "BodyNormD"
![Screenshot (650)](https://user-images.githubusercontent.com/78466408/173252973-33109816-8639-4534-b0b4-15245d3a8ccd.png)


And then added this line of code to the "importeverything.py" script
![Screenshot (651)](https://user-images.githubusercontent.com/78466408/173252993-ca75f4a2-2ce6-4367-8714-85f23874ef45.png)

Now they at least load in the textures group. I'm gonna update my stuff rn and see if the 3 Sleeves curse is gone. I was getting it on a LOT of outfits. 

> Thanks for all the testing!

You saved me SO much time by adding KKS support so the thanks really goes to you. Sorry for initially doubting you.

**Comment by poisenbery** [comment]
3 Sleeves curse is gone. The console spits out warnings instead of stopping now. Yay!

**Comment by FlailingFog** [comment]
>I found a minor hiccup with the detail map texture.

To be honest, I'm not sure what that's used for...

**Comment by MediaMoots** [comment]
> the detail map texture.

This adds detail to the normal map.

Check this out:
https://github.com/xukmi/KKShadersRecreated/blob/e43980ee14c3a4b50dab2f0b45408125fb7b78d3/Shaders/Skin/KKNormals.cginc#L4

**Comment by poisenbery** [comment]
> I'm not sure what that's used for...

Based on what I've found, all of the body line masks have an additional normal map.
The line masks seem to have 2 parts: the color mask and the associated detail normal map [NMPD].
You already know how the color aspect works: it uses the line mask to simulate details on the body with different colors.
This effect is further enhanced by the detail normal map.


Here's what it looks like:
No normal maps:
![Screenshot (655)](https://user-images.githubusercontent.com/78466408/173276261-af2016a6-1e47-4083-95cc-d5381453eb90.png)

Normal Map:
![Screenshot (657)](https://user-images.githubusercontent.com/78466408/173276295-2074b6d0-3ce0-4ee9-8c65-1fa768b4a067.png)

Normal Map + Detail Normal Map:
![Screenshot (656)](https://user-images.githubusercontent.com/78466408/173276325-633af5de-b515-48aa-9fd0-5fedac43cd5d.png)

**Comment by FlailingFog** [comment]
@MediaMoots 
So the BlendNormals function in Unity seems to perform a whiteout type of normal blending, and https://blog.selfshadow.com/publications/blending-in-detail/ says that a whiteout blend can be achieved with
```
float3 r = normalize(float3(normal1.xy + normal2.xy, normal1.z*normal2.z));
```
or
```
x and y = (normal1.xy + normal2.xy) / sqrt( 2 * (normal1.xy + normal2.xy) ^2 + 1) 
z       = 1/sqrt( 2 * (normal1.xy + normal2.xy) ^2 + 1)
```

I also see from https://github.com/Perfare/AssetStudio/issues/593 that the normal map alpha can be used to fill in the X and Y channels of the normal, with the Z channel as 1, so that can be replicated in shader nodes with this...
![image](https://user-images.githubusercontent.com/65811931/173820168-506125cb-70b5-44f5-8b21-369a987a8f64.png)

But that produces a gray normal map like the image below. I'm expecting a purple normal map, so I feel like I'm not using the texture correctly.
![image](https://user-images.githubusercontent.com/65811931/173820637-e5db78f9-fb46-41ca-a989-c30f702cba5b.png)

Dividing the normal1.xy and normal2.xy by a factor of two produces something that looks correct though. 
![image](https://user-images.githubusercontent.com/65811931/173821098-54cf2f13-f822-45f4-96b0-6ab41e89e257.png)
Do you know if using the just the alpha channel by itself is the correct way to reproduce the normal map, or do you have to do something else to it?

@poisenbery 
How are you applying the second normal map?

**Comment by poisenbery** [comment]
> How are you applying the second normal map?

```

float3 n1 = tex2D(texBase,   uv).xyz*2 - 1;
float3 n2 = tex2D(texDetail, uv).xyz*2 - 1;

float3x3 nBasis = float3x3(
    float3(n1.z, n1.y, -n1.x), // +90 degree rotation around y axis
    float3(n1.x, n1.z, -n1.y), // -90 degree rotation around x axis
    float3(n1.x, n1.y,  n1.z));

float3 r = normalize(n2.x*nBasis[0] + n2.y*nBasis[1] + n2.z*nBasis[2]);
return r*0.5 + 0.5;

```

**Comment by MediaMoots** [comment]
Thats pretty good, here is the source code for that function
https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/6a63f93bc1f20ce6cd47f981c7494e8328915621/CGIncludes/UnityStandardUtils.cginc#L144

**Comment by FlailingFog** [comment]
Thanks for the extra info. I put both methods into the "Raw shading" group

> There are....a few ways to do it. Just don't use a mix RGB node lol

I originally had a toggle for swapping between the whiteout normals and your node group, but both the mixRGB and the mix shader nodes weren't working, so you may be on to something...

**Comment by poisenbery** [comment]
> But that produces a gray normal map like the image below. I'm expecting a purple normal map, so I feel like I'm not using the texture correctly.

I just checked this over and thought I'd provide some feedback:

It looks like you're using standard math nodes to combine vector values.
You have to remember that grey input sockets are float values, not vectors.
I'm pretty sure all you are doing is combining everything into 1 x component since you aren't using vector math nodes, nor any separate/combine XYZ nodes. 

This would explain why the texture is white and not tangent space: you're combining everything into X and there is no Y or Z information.

**Comment by poisenbery** [comment]
"Export Variations" does not check for additional outfit slots.

Any character in KK that has an additional outfit slot will not have that outfit exported.
In KKS, the default outfit slots are 4, so any KK card used in KKS will only have the first 4 outfits exported.

The additional outfit slots in KKS seem to cause a game-breaking bug with the "Breast Physics Controller" mod. Console goes insane, multiple outfits can be selected at once, and the options to change the outfits disappears entirely
![Screenshot (705)](https://user-images.githubusercontent.com/78466408/175532981-afc46d88-5870-4478-94d2-8714aaa7236d.png)
![Screenshot (706)](https://user-images.githubusercontent.com/78466408/175532990-220f3833-bcbd-40d4-b4ab-fe3ad99d61e9.png)
.


Doesn't happen if you disable the controller for that card. Should be done BEFORE swapping outfits.
![Screenshot (707)](https://user-images.githubusercontent.com/78466408/175533641-266bc18e-9dbe-4f29-9509-0e5a171ecf57.png)
.

**Comment by poisenbery** [comment]
> "Export Variations" does not check for additional outfit slots.
> 
> Any character in KK that has an additional outfit slot will not have that outfit exported. In KKS, the default outfit slots are 4, so any KK card used in KKS will only have the first 4 outfits exported.


@MediaMoots Is it still recommended to not use the current version of the PR? I found some other bugs, but then I noticed this, so I didn't post anything about them.: https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138#issuecomment-1161338393

**Comment by MediaMoots** [comment]
@poisenbery You are going to need to ask @FlailingFog about that because I haven't tested the Blender Import pipeline.

> Any character in KK that has an additional outfit slot will not have that outfit exported.

Fixed in KK and probably fixed in KKS: V3.66 [ad1e80c](https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138/commits/ad1e80c94e415c707de23efd93d4a2789f798127)

**Comment by FlailingFog** [comment]
The default options for the blender plugin should work now. The "Rigify armature" option and "Pause to categorize" option should also work.

**Comment by poisenbery** [comment]
> > 
> 
> Fixed in KK and probably fixed in KKS



> 
@MediaMoots 
Confirmed fixed! Yay.
But, it now will ONLY export all outfits.
It also doesn't seem to play nicely with the Pushup mod. 
Pushup changes the chest shape per outfit, but it seems like export variations only exports one body, so any card affected by pushup will have the breasts misaligned with the top itself. For bathing suits and other types of revealing clothing, the alpha mask cannot fix the problem. 


@FlailingFog 
I checked the import process and I didn't notice any problems.

**Comment by MediaMoots** [comment]
> But, it now will ONLY export all outfits.

it's all or nuthn' ma man!
Jk, maybe I'll add an option to only export the current outfit, lol.

> It also doesn't seem to play nicely with the Pushup mod.

Impressed you found this issue so quickly; It took me a bit to figure that one out.
I think the only way it can be fixed is to just disable pushups during the export, I'll deal with that in a bit. (Working on some other features now)

> One other thing I noticed is that multiple exports seem to take an extremely long time

Ok, thanks for the feedback.

**Comment by MediaMoots** [comment]
@poisenbery 

Check out [72b9efb](https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138/commits/72b9efb4930a588f173cac755c3a196100a00c09) 
: )

**Comment by poisenbery** [comment]
> Impressed you found this issue so quickly; It took me a bit to figure that one out.

https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/84#issuecomment-1019560727

I am actually psychic.

**Comment by poisenbery** [comment]
> Check out [72b9efb](https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138/commits/72b9efb4930a588f173cac755c3a196100a00c09)

It still refuses to do single outfit exports in KKS =/

**Comment by MediaMoots** [comment]
> https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/84#issuecomment-1019560727

> I am actually psychic.

![image](https://user-images.githubusercontent.com/81146974/177449661-125fad82-fa90-45b3-a238-119c9371ecf3.png)

> It still refuses to do single outfit exports in KKS =/

It can't refuse what it wasn't made to do;
![image](https://user-images.githubusercontent.com/81146974/177449910-7962f41a-9a46-4494-a382-7270c6476f99.png)
Soon tho, soon.

**Comment by poisenbery** [comment]
> It can't refuse what it wasn't made to do;

ahhhh my bad. the overload of anime girls seems to be having a negative effect on my reading comprehension
